import Head from 'next/head';

export default function Meta() {
	return (
		<Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
            <link href="/dist/output.css" rel="stylesheet"></link>
            <link rel="icon" href="/favicon.ico" />
		</Head>
	)
}