import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/BlogPage.module.css'

const BlogPage: NextPage = (/* { blogVariable }: { blogVariable: Blog } */) => {  // types come from types.ts
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Specific blog page</h1>
    </div>
  )
}

export const getStaticPaths = async () => {

    // fetch contentful blogs

    /*
    return {
        paths: results.map((blog) => {
            return { params: { id: String(blog.id)}}
        })
    }
    */
}

export const getStaticProps = async ({params}: { params: { id: string } }) => { 

    // fetch the specific blog

    /*
    return {
        props: {
            blogVariable
        }
    }
    */
}

export default BlogPage;