import Head from "next/head";
import { useRouter } from "next/router";
import BlogList from "../../components/BlogList";

import Header from "../../components/Header";
import { getBlogPageLanding } from "../../utils/api"

export default function BlogPage ({pageLanding}) {
    const headerData = {
        headerCollection: {
            items: [{...pageLanding?.sectionsCollection?.items[0]}]
        }
    }

    const blogsCollection = pageLanding?.sectionsCollection?.items?.find((section) => section.blogsCollection);
    const categories = pageLanding?.sectionsCollection?.items?.find((section) => section.categoriesCollection);

    const router = useRouter();

    return (
        <div>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css"></link>
            </Head>
            <header>
                <Header headerData={headerData}/>
            </header>
            <main>
                <BlogList blogsCollection={blogsCollection} categories={categories}/>
            </main>
        </div>
    )
}

export async function getStaticProps () {
    
    const data = await getBlogPageLanding();

    return {
        props: {
            ...data
        }
    }
}