import { getAllLandingTypes, getLandingBySlug, getPreviewLandingBySlug } from "../utils/api"
import Head from "next/head";
import { Layout } from "../components/Layout";

export default function page (props) {
  return (
    <div>
      <Head>
        <title>landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css"></link>
      </Head>
      <main className='relative'>
        <Layout landingData={props.landingData} preview={props.preview}/>
      </main>
    </div>
  )
}

export async function getStaticPaths() {

    const landings = await getAllLandingTypes();
    
    return {
        paths: landings.map((landing) => {
            return { params: { slug: landing.fields.slug }}
        }) ?? [],
        fallback: true
    }
}

export async function getStaticProps(context) {

  const client = context.preview ? getPreviewLandingBySlug(context.params.slug) : getLandingBySlug(context.params.slug);

  const landingData = await client;

  return {
      props: {
        preview: context.preview || false,
        landingData
      }
  }
}