import type { GetStaticProps, NextPage } from 'next'
import { responseSymbol } from 'next/dist/server/web/spec-compliant/fetch-event'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage/*<{ exampleVariable: ExampleType }> from types.ts*/ = (props/*{ exampleVariable }*/) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{JSON.stringify(props)}</div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  
  const response = await fetch(`https://cdn.contentful.com/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master/entries?access_token=${process.env.CONTENTFUL_ACCESS_TOKEN}&content_type=setOfCard`);
  const items = await response.json();

  return {
    
    props: {
      items: items.items,
    }
  }
}

export default Home
