import { GetStaticProps, NextPage } from 'next'
import { responseSymbol } from 'next/dist/server/web/spec-compliant/fetch-event'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header';
import HeroImage from '../components/HeroImage';
import CardsSection from '../components/CardsSection';
import { Layout } from '../components/Layout';

import Icon from '@mdi/react'
import styles from '../styles/Home.module.css'
import { getHomeLandingPageData, getAllCardData, getAllHeaderData, getAllTestimonialData, getCardSectionData, getHeroImageData } from '../utils/api'
import SectionCard from '../components/SectionCard';
import TestimonialSection from '../components/TestimonialSection';

  //<HeroImage heroImageCollection={props.heroImageData}/>
  //<CardsSection cardData={props.cardData} style={"icon"}/>
  //<CardsSection cardData={props.cardData} style={"image"}/>
  //<SectionCard sectionData={props.sectionData} />
  //<TestimonialSection testimonialData={props.testimonialData}/>

const Home = (props = null) => {

  console.log(props.landingData)

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css"></link>
      </Head>
      <main className='relative'>
        <Layout landingData={props.landingData}/>
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const landingData = await getHomeLandingPageData();

  return {
    props: {
      landingData
    }
  }
}

export default Home
