import Head from 'next/head'
import { Layout } from '../components/Layout';
import { getHomeLandingPageData } from '../utils/api'

const Home = (props = null) => {

  console.log(props.landingData)

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css" />
      </Head>
      <main className='relative w-full'>
        <Layout landingData={props.landingData}/>
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const landingData = await getHomeLandingPageData();

  return {
    props: {
      landingData
    }
  }
}

export default Home
