import { GetStaticProps, NextPage } from 'next'
import { responseSymbol } from 'next/dist/server/web/spec-compliant/fetch-event'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header';
import HeroImage from '../components/HeroImage';
import CardsSection from '../components/CardsSection';

import Icon from '@mdi/react'
import styles from '../styles/Home.module.css'
import { getAllCardData, getAllHeaderData, getAllTestimonialData, getCardSectionData, getHeroImageData } from '../utils/api'
import SectionCard from '../components/SectionCard';
import TestimonialSection from '../components/TestimonialSection';



const Home = (props = null) => {

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css"></link>
      </Head>
      <header>
        <Header headerData={props.headerData}/>
      </header>
      <main className='relative'>
        <HeroImage heroImageCollection={props.heroImageData}/>
        <CardsSection cardData={props.cardData} style={"icon"}/>
        <CardsSection cardData={props.cardData} style={"image"}/>
        <SectionCard sectionData={props.sectionData} />
        <TestimonialSection testimonialData={props.testimonialData}/>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {

  const headerData = await getAllHeaderData();
  const heroImageData = await getHeroImageData();
  const cardData = await getAllCardData();
  const sectionData = await getCardSectionData();
  const testimonialData = await getAllTestimonialData();

  return {
    
    props: {
      headerData: headerData,
      heroImageData: heroImageData,
      cardData: cardData,
      sectionData: sectionData,
      testimonialData: testimonialData,
    }
  }
}

export default Home
